### ISSUE TITLE
Messaging API - August 2020 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-go#222]
News: https://developers.line.biz/en/news/2020/08/04/messaging-api-update-august-2020/

- [x] [Unsend event has been added](https://developers.line.biz/en/reference/messaging-api/#unsend-event)
- [x] [Video viewing complete event has been added](https://developers.line.biz/en/reference/messaging-api/#video-viewing-complete)
- [ ] [The audiences property is now optional instead of required for a certain endpoint](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group)
- [ ] [Create audience for uploading user IDs (by file)](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group-by-file)
- [ ] [Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by file](https://developers.line.biz/en/reference/messaging-api/#update-upload-audience-group-by-file)

**Comment by kkdai** [comment]
https://github.com/line/line-bot-sdk-go/pull/223 for the unsend and video viewing complete

**Comment by justdomepaul** [comment]
@tkgauri @kkdai 

My commit is finish managing audience api sdk in this [pr](https://github.com/line/line-bot-sdk-go/pull/302)

Maybe it can help to resolve issue

- [The audiences property is now optional instead of required for a certain endpoint](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group)
- [Create audience for uploading user IDs (by file)](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group-by-file)
- [Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by file](https://developers.line.biz/en/reference/messaging-api/#update-upload-audience-group-by-file)
