### ISSUE TITLE
Webhook example

### ISSUE THREAD

**Issue by huyjack178** [line/line-bot-sdk-go#41]
Hi, I am starting using Line Bot SDK, I want to send message to all Bot's friend. I know that webhook can know IDs of all Bot's friend. Is there any example?

**Comment by GuitarSucks** [comment]
@huyjack178 
The webhook will not return all BOT's friend ID's. It will only return events that occurred with the userId. We also don't have any API to retrieve them. 
If you don't have all the ID's of your BOT's friend, you can still send broadcast messages from LINE @ Manager.

**Comment by huyjack178** [comment]
Thanks, I want to send message to all Bot's friend at the same time. How can I do this?

**Comment by huyjack178** [comment]
And another thing is, how can I use my local webhook URL. Please tell me is it possible. Thanks a lot

**Comment by GuitarSucks** [comment]
`Thanks, I want to send message to all Bot's friend at the same time. How can I do this?`
-> You can only do so by calling multicast API several times. To use it you will need a plan that can use push api.

`And another thing is, how can I use my local webhook URL. Please tell me is it possible. Thanks a lot`
-> You mean you want to use localhost ? If so its not possible since our platform needs to communicate to send any event.

**Comment by huyjack178** [comment]
> -> You can only do so by calling multicast API several times. To use it you will need a plan that can use push api.
Many thanks, it is free, right?

> You mean you want to use localhost ? If so its not possible since our platform needs to communicate to send any event.
Yes, I want to debug in localhost, so can not do it, right?
