### ISSUE TITLE
New LIFF API and Flex Message API PR Code Review

### ISSUE THREAD

**Issue by justdomepaul** [line/line-bot-sdk-go#84]
https://github.com/line/line-bot-sdk-go/pull/83

I PR a latest version, please code review and merge to master.

Thanks.

**Comment by sugyan** [comment]
Thanks for your contribution!
I have some comments...

- Please use `gofmt`. Align the indents and use tab instead of spaces.
- Since "Flex messages" and "LIFF" are different functions, we want pull-requests to be separated.
  - BTW, I was preparing for flex messages... https://github.com/sugyan/line-bot-sdk-go/tree/flex-messages
- `.gitignore` for files not related to Go language should be set by each developer in `git config --global core.excludesfile` etc. It should not be included in pull-request.

**Comment by justdomepaul** [comment]
@sugyan 

Thanks for your feedback!

I will handle some point.
* fmt all changed go file
* new two branch to separeate "Flex Messages" and "LIFF" function to different PR.
* recovery origin .gitignore file

ps. I think your "Flex Messages" solution is better than my solution. It is a good point to solve complex struct of "Flex Message".

**Comment by sugyan** [comment]
This has been updated by #89, so I close it.
